
services:
  clickhouse-backup:
    image: altinity/clickhouse-backup:2.6.3
    restart: always
    command: ["/bin/bash", "/init.sh"]
    volumes:
      - ./init.sh:/init.sh
      - /data/clickhouse:/data/clickhouse
    environment:
      - CLICKHOUSE_HOST=localhost
      - CLICKHOUSE_USERNAME=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - S3_BUCKET=wotstat-backup
      - S3_ENDPOINT=https://storage.yandexcloud.net
      - S3_REGION=ru-central1
      - S3_STORAGE_CLASS=STANDARD_IA # <==> COLD
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - REMOTE_STORAGE=s3
      - WATCH_INTERVAL=24h
      - FULL_INTERVAL=504h
    network_mode: "host"